env:
  node: true
  browser: true
  jest: true

plugins:
  - jest

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  import/extensions: 0
  no-underscore-dangle: off

parserOptions:
  ecmaVersion: 2020
  sourceType: module
